-- SQL Schema para Barão da Torre
-- Copie e cole este código no SQL Editor do seu projeto Supabase

-- 1. APAGAR TABELAS EXISTENTES (PARA GARANTIR INSTALAÇÃO LIMPA)
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS online_classes CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS app_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CRIAR TABELA DE USUÁRIOS
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  course TEXT,
  semester INT DEFAULT 1,
  validity TEXT DEFAULT '12/2026',
  regularity TEXT DEFAULT 'Regular',
  cpf TEXT,
  birth_date TEXT,
  enrollment_date TEXT,
  birth_state TEXT,
  nationality TEXT,
  gender TEXT,
  marital_status TEXT,
  short_name TEXT,
  email TEXT UNIQUE,
  address TEXT,
  city TEXT,
  cep TEXT,
  role TEXT DEFAULT 'student' CHECK (role IN ('admin', 'student')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
  photo_url TEXT,
  enrollment_proof_url TEXT,
  enrollment_proof_urls JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CRIAR TABELA DE CONFIGURAÇÕES
CREATE TABLE app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logo_url TEXT DEFAULT 'https://cdn-icons-png.flaticon.com/512/3135/3135810.png',
  primary_color TEXT DEFAULT '#1fbba6',
  secondary_color TEXT DEFAULT '#0066cc',
  theme TEXT DEFAULT 'barao',
  college_name TEXT DEFAULT 'Barão da Torre',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CRIAR DEMAIS TABELAS
CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  professor TEXT,
  room TEXT,
  day_of_week TEXT,
  time TEXT,
  course TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  discipline_id BIGINT,
  discipline_name TEXT,
  grade_b1 NUMERIC DEFAULT 0,
  grade_b2 NUMERIC DEFAULT 0,
  final_grade NUMERIC DEFAULT 0,
  absences INT DEFAULT 0,
  status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  date TEXT,
  important BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  due_date TEXT,
  status TEXT DEFAULT 'Em aberto' CHECK (status IN ('Pago', 'Em aberto')),
  pix_code TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  hours INT DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('approved', 'pending', 'rejected')),
  certificate_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discipline_id BIGINT,
  discipline_name TEXT,
  date TEXT,
  time TEXT,
  type TEXT,
  course TEXT,
  link TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE online_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discipline_id BIGINT,
  discipline_name TEXT,
  course TEXT,
  link TEXT,
  date TEXT,
  day_of_week TEXT,
  time TEXT,
  mandatory BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image TEXT,
  date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. INSERIR DADOS INICIAIS
INSERT INTO users (matricula, password, name, role, status)
VALUES ('admin', 'admin', 'Administrador Sistema', 'admin', 'active');

INSERT INTO app_settings (college_name, theme, primary_color, secondary_color)
VALUES ('Barão da Torre Academy', 'barao', '#1fbba6', '#0066cc');

-- 6. DESATIVAR RLS (PARA PERMITIR RESTAURAÇÃO DE DADOS PELO APP)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE grades DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE online_classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE news DISABLE ROW LEVEL SECURITY;
